application: volcanicpixels-staging
version: live

runtime: python27
threadsafe: true
api_version: 1
automatic_scaling:
  max_idle_instances: 1  # default value
  min_pending_latency: 2s  # default value
  max_concurrent_requests: 20

handlers:
- url: /assets
  static_dir: assets

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /api/1/.*
  script: volcanicpixels.legacy.app


- url: /ssl.*
  script: volcanicpixels.frontend.app
  secure: always

- url: .*
  script: volcanicpixels.frontend.app
  secure: always

inbound_services:
- warmup

builtins:
- deferred: on

libraries:
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
